class Property:  
    def __init__(self, 
    listing_name,
    total_price,
    listing_address,
    listing_title,
    listing_write_up,
    bedrooms,
    bathrooms,
    garages,
    garden,
    pet_friendly,
    listing_number,
    property_type,
    street_address,
    list_date,
    lot_area,
    floor_area,
    price_per_sqm,
    broker_name,
    broker_contact_number,
    broker_email,
    url):
        self.listing_name=listing_name
        self.total_price=total_price
        self.listing_address=listing_address
        self.listing_title=listing_title
        self.listing_write_up=listing_write_up
        self.bedrooms=bedrooms
        self.bathrooms=bathrooms
        self.garages=garages
        self.garden=garden
        self.pet_friendly=pet_friendly
        self.listing_number=listing_number
        self.property_type=property_type
        self.street_address=street_address
        self.list_date=list_date
        self.lot_area=lot_area
        self.floor_area=floor_area
        self.price_per_sqm=price_per_sqm
        self.broker_name=broker_name
        self.broker_contact_number=broker_contact_number
        self.broker_email=broker_email
        self.url=url